export default [
    {
        positionTitle: "Software Engineer",
        employmentType: "Full-time",
        companyName: "Tech Innovations Inc.",
        startDate: "2022-03-15",
        endDate: "2023-06-30",
        responsibilities: ["Developing new features", "Bug fixing", "Code review"],
    },
    {
        positionTitle: "Marketing Specialist",
        employmentType: "Contract",
        companyName: "Global Marketing Solutions",
        startDate: "2021-09-10",
        endDate: "2022-02-28",
        responsibilities: ["Creating marketing campaigns", "Analyzing market trends", "Social media management"],
    },
    {
        positionTitle: "Project Manager",
        employmentType: "Part-time",
        companyName: "Project Management Co.",
        startDate: "2020-05-20",
        endDate: "2021-12-15",
        responsibilities: ["Leading project teams", "Budget management", "Client communication"],
    },
    {
        positionTitle: "Data Scientist",
        employmentType: "Full-time",
        companyName: "Data Analytics Corp.",
        startDate: "2019-02-10",
        endDate: "2020-04-30",
        responsibilities: ["Analyzing data sets", "Building machine learning models", "Data visualization"],
    },
    {
        positionTitle: "Graphic Designer",
        employmentType: "Freelance",
        companyName: "Creative Designs Studio",
        startDate: "2018-07-15",
        endDate: "2019-01-05",
        responsibilities: ["Designing visual assets", "Brand identity creation", "Collaborating with clients"],
    },
    {
        positionTitle: "HR Coordinator",
        employmentType: "Full-time",
        companyName: "Human Resources Ltd.",
        startDate: "2017-03-01",
        endDate: "2018-05-10",
        responsibilities: ["Recruitment process", "Employee onboarding", "HR policy implementation"],
    },
    {
        positionTitle: "Financial Analyst",
        employmentType: "Internship",
        companyName: "Financial Consulting Services",
        startDate: "2016-09-05",
        endDate: "2017-02-28",
        responsibilities: ["Financial data analysis", "Preparing reports", "Assisting in budgeting"],
    },
    {
        positionTitle: "Customer Support Representative",
        employmentType: "Full-time",
        companyName: "Customer Solutions Inc.",
        startDate: "2015-04-20",
        endDate: "2016-08-15",
        responsibilities: ["Assisting customers", "Resolving issues", "Providing product information"],
    },
    {
        positionTitle: "Legal Assistant",
        employmentType: "Part-time",
        companyName: "Law Firm Associates",
        startDate: "2014-01-10",
        endDate: "2015-03-25",
        responsibilities: ["Legal research", "Drafting legal documents", "Client communication"],
    },
    {
        positionTitle: "Sales Representative",
        employmentType: "Full-time",
        companyName: "Sales Dynamics Co.",
        startDate: "2013-06-15",
        endDate: "2014-01-05",
        responsibilities: ["Sales prospecting", "Negotiating contracts", "Meeting sales targets"],
    },
];
